### ISSUE TITLE
Overfitting

### ISSUE THREAD

**Issue by EthixLucifer** [Sudhanshu-Ambastha/Multiple-Disease-Prediction-Bot#1]
The models are giving 100% accuracy in both training and testing phase. The model is overfitted, is there any solution to eliminate ovefitting of the models.

**Comment by Sudhanshu-Ambastha** [comment]
@EthixLucifer- Hi, first of all thank you for visiting my repository (repo) and posting your valuable comments. My model is working perfectly as I wanted its prediction 100% perfect and I have tested it on many test subjects also and max test subjects had accepted that they are currently suffering from the problem which the machine had predicted so my prediction is successful for which it is meant for. Regarding your query I would like to suggest that if you feel like the model is overfitted just reduce the number of parameters for prediction or change the dataset. Feel free to ask any other query and if you like it give it a star 🌟 as it motivates me to come up with ideas like these and follow me for upcoming models or updates
